const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('main/dashboard.js','utf8');
const ctx=vm.createContext({Math,Number,reasons:{meter:'Wallbox-Zähler fehlt'},powerFactor:n=>.23*n});
vm.runInContext(source.slice(source.indexOf('function controlStatus('),source.indexOf('function render(){')),ctx);
const base={enabled:true,block_reason:'none',phase_switch_enabled:true,phase_state:'bereit',phase_wait_kind:'none',charge_phases:1,feedback_ok:true,actual_a:[11,11,11],estimate_w:2530,target_current_a:11,mode:'manual'};
const status=(extra={},valid=true)=>ctx.controlStatus({...base,...extra},valid);
assert.match(status().text,/Lädt · 1-phasig/);
assert.match(status({},false).text,/nicht aktuell/);
assert.match(status({enabled:false,actual_a:[.1,.1,.1]}).text,/ausgeschaltet/);
assert.match(status({enabled:false}).text,/Stopp angefordert/);
assert.equal(status({phase_state:'fehler'}).kind,'fault');
assert.match(status({phase_state:'stoppen',phase_wait_kind:'zero_hold',phase_wait_s:7}).text,/stromlose Wartezeit · noch 7 s/);
assert.match(status({phase_state:'schalten',phase_wait_kind:'contact',phase_wait_s:4}).text,/Rückmeldung · höchstens noch 4 s/);
assert.match(status({phase_state:'pruefen',phase_wait_kind:'fresh_data',phase_wait_s:20}).text,/frische Messwerte · höchstens noch 20 s/);
assert.match(status({charge_retry_s:25}).text,/Wiederanlauf · noch 25 s/);
assert.match(status({block_reason:'pv_starting',pv_wait_s:30}).text,/vor dem Start prüfen · noch 30 s/);
assert.match(status({block_reason:'meter',actual_a:[null,null,null],feedback_ok:false}).text,/Zähler fehlt/);
assert.match(status({actual_a:[.1,.1,.1]}).text,/warte auf Fahrzeug/);
assert.match(status({phase_wait_kind:'hold',phase_wait_s:290}).text,/frühestens in 290 s/);
assert.match(status({battery_buffer_active:true,battery_buffer_remaining_s:121}).text,/Wolkenpuffer 3 min/);
assert(!fs.readFileSync('main/dashboard.html','utf8').includes('relay-card'));
let unlock,request;
const ui=vm.createContext({$:()=>({addEventListener:(event,callback)=>{unlock=callback;}}),
  action:fn=>fn(),api:async(path,body)=>{request={path,body};},pollStatus:async()=>{},toast:()=>{}});
const first=source.indexOf("$('unlock-control').addEventListener('click'");
vm.runInContext(source.slice(first,source.indexOf('\n',first)),ui);
(async()=>{await unlock();assert.equal(request.path,'/api/control');assert.equal(request.body.enabled,false);assert.equal(request.body.restart,true);
console.log('PASS: countdowns, charging, retry and stale data; unlocking leaves charging stopped');
})().catch(error=>{console.error(error);process.exitCode=1;});
