const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('main/dashboard.js','utf8');
const code=src.slice(src.indexOf('function updateUnsavedFunctions(){'),src.indexOf("$('config-form').addEventListener('input',updateUnsavedFunctions)"));
const price={name:'price_kwh',type:'number',value:'.25',dataset:{},hasAttribute:()=>false};
const secret={name:'mqtt_password',type:'password',value:'',dataset:{},hasAttribute:a=>a==='data-secret'};
const nodes={'config-form':{elements:[price,secret]},'clear-wifi-password':{checked:false},'opendtu-enabled':{checked:false}};
for(const id of ['functions-unsaved','settings-notice-title','settings-notice-icon','settings-notice-text','settings-notice-save','settings-notice-restart-actions'])nodes[id]={hidden:true,textContent:'',dataset:{}};
const c={Array,Math,Number,configBaseline:{price_kwh:.25,mqtt_input_source:0},initialized:true,settingsRebootPending:false,settingsRebootDeferred:false,$:id=>nodes[id]};
vm.createContext(c);vm.runInContext(code,c);
const update=()=>c.updateUnsavedFunctions();
update();assert.equal(nodes['functions-unsaved'].hidden,true);
price.value='.26';update();assert.equal(nodes['functions-unsaved'].hidden,false);
price.value='.25';update();assert.equal(nodes['functions-unsaved'].hidden,true);
secret.value='demo-secret';update();assert.equal(nodes['functions-unsaved'].hidden,false);
secret.value='';c.settingsRebootPending=true;update();assert.equal(nodes['settings-notice-title'].textContent,'Neustart erforderlich');assert.equal(nodes['settings-notice-save'].hidden,true);assert.equal(nodes['settings-notice-restart-actions'].hidden,false);
c.settingsRebootDeferred=true;update();assert.equal(nodes['functions-unsaved'].hidden,true);
price.value='.26';update();assert.equal(nodes['functions-unsaved'].hidden,false);assert.equal(nodes['settings-notice-restart-actions'].hidden,true);
price.value='.25';update();assert.equal(nodes['functions-unsaved'].hidden,true);
c.settingsRebootPending=false;c.settingsRebootDeferred=false;update();assert.equal(nodes['functions-unsaved'].hidden,true);
assert.equal(c.updateSaveStatus({reboot_required:true,applied:false,restart_needed:true}),true);
c.settingsRebootDeferred=true;
assert.equal(c.updateSaveStatus({reboot_required:true,applied:true,restart_needed:false}),false);
assert.equal(c.settingsRebootDeferred,true,'live saves preserve a postponed restart');
update();assert.equal(nodes['functions-unsaved'].hidden,true);
assert.equal(c.updateSaveStatus({reboot_required:true,applied:false,restart_needed:true}),true);
assert.equal(c.settingsRebootDeferred,false,'new hardware changes show their restart requirement');
c.updateSaveStatus({reboot_required:false,applied:true,restart_needed:false});
update();assert.equal(nodes['functions-unsaved'].hidden,true);
assert(!src.includes("toast(result.reboot_required?'Gespeichert. Bitte neu starten.'"));
assert(src.includes("$('config-note').hidden=true;for(const el"));
console.log('PASS: single notice, saved secrets, reverted edits, pending and deferred restart');
