const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),calls=[],events=new Map();
function node(id){if(!elements.has(id))elements.set(id,{id,hidden:false,disabled:false,dataset:{},value:'',textContent:'',classList:{toggle(){}},setAttribute(){},closest(){return node('panel')},addEventListener(type,fn,capture){events.set(`${id}:${type}`,{fn,capture})}});return elements.get(id)}
let pending;
const context={online:true,busy:false,token:'test-token',state:{evcc_test_enabled:true,enabled:false,evcc_status_known:true},location:{hash:'#overview',host:'esp.local'},document:{getElementById:node,querySelector:node,querySelectorAll:()=>[]},window:{addEventListener(){}},api:async(path,body)=>{calls.push({path,body});return{}},pollStatus:async()=>{},toast(){},action:fn=>{pending=fn()},Blob,URL,setTimeout};
vm.createContext(context);
vm.runInContext(fs.readFileSync('main/evcc-test.js','utf8'),context);
context.window.teenetEvccTest.updateWrites(context.state);
assert.equal(node('evcc-owner-banner').hidden,false);
assert.equal(node('mqtt-evcc-note').hidden,false);
assert.equal(node('apply-control').textContent,'Lokal stoppen');
assert.equal(node('apply-control').disabled,false,'A stopped charger still permits a local inhibit');
const submit=events.get('control-form:submit');assert.equal(submit.capture,true);
(async()=>{
 let prevented=false,blocked=false;
 submit.fn({preventDefault(){prevented=true},stopImmediatePropagation(){blocked=true}});
 await pending;
 assert(prevented&&blocked,'Existing manual-start handler must not receive evcc submit');
 assert.equal(calls.length,1);
 assert.equal(calls[0].path,'/api/control');
 assert.equal(calls[0].body.enabled,false);assert.equal(calls[0].body.mode,'off');
 context.state.evcc_local_stop=true;
 context.window.teenetEvccTest.updateWrites(context.state);
 assert.equal(node('apply-control').textContent,'evcc freigeben');
 assert.equal(node('apply-control').disabled,false);
 submit.fn({preventDefault(){},stopImmediatePropagation(){}});
 await pending;assert.equal(calls.length,2);assert.equal(calls[1].path,'/api/evcc/local_release');assert.equal(calls[1].body.release,true);
 context.window.teenetEvccTest.updateWrites({basic_mode:true});
 assert.equal(node('evcc-owner-banner').hidden,true);
 assert.equal(node('mqtt-evcc-note').hidden,true);
 assert.equal(node('.mode-picker').hidden,true,'Basic mode stays compact without evcc');
 const cfg={key:'private-example',phase_switch_supported:true,min_current_a:8.7,max_current_a:16};
 const generated=context.window.teenetEvccTest.yaml(cfg,'TeeNet.local');
 assert(generated.includes('http://TeeNet.local/api/evcc/status'));
 assert(generated.includes('token: "private-example"'));
 assert(generated.includes('mincurrent: 8.7'));
 assert(generated.includes('maxcurrent: 16'));
 assert(generated.includes('phases: 0'));
 assert(!generated.includes('192.168.1.162'),'No personal evcc address in generated config');
 assert(!generated.includes('192.168.1.166'),'ESP address is taken from current browser host');
 const other=context.window.teenetEvccTest.yaml({...cfg,min_current_a:9,max_current_a:13,phase_switch_supported:false,phases:3},'192.168.178.42');
 assert(other.includes('http://192.168.178.42/api/evcc/status'));
 assert(other.includes('mincurrent: 9'));
 assert(other.includes('maxcurrent: 13'));
 assert(!other.includes('phases1p3p:'));
 console.log('PASS: evcc ownership, local stop, MQTT clarification and user-specific generated configuration');
})().catch(error=>{console.error(error);process.exitCode=1});
